In [16]:
# ICP2 Assingment
# Author: Gopi Reddy Pallerla
#code: python


#Q 1

# Employee class definition
class Employee:
    # Class variable to count the number of employees
    employee_count = 0

# Constructor to initialize employee details
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1  # Increment employee count when an employee is created

    # Method to calculate the average salary of all employees
    @classmethod
    def average_salary(cls, employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees) if employees else 0

    # Display employee details
    def display_employee(self):
        print(f"Name: {self.name}, Family: {self.family}, Salary: {self.salary}, Department: {self.department}")

# FulltimeEmployee class inheriting from Employee class
class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, bonus):
        # Call the constructor of the Employee class
        super().__init__(name, family, salary, department)
        self.bonus = bonus  # Additional data member for FulltimeEmployee class

    # Display fulltime employee details along with bonus
    def display_fulltime_employee(self):
        print(f"Name: {self.name}, Family: {self.family}, Salary: {self.salary}, Department: {self.department}, Bonus: {self.bonus}")

# Create instances of Employee and FulltimeEmployee
emp1 = Employee("Gopi", "Reddy", 60000, "Market")
emp2 = Employee("eswar", "Bhai", 70000, "Finance")
emp3 = FulltimeEmployee("mahesh", "babu", 80000, "hero", 5000)
emp4 = FulltimeEmployee("anushka", "shetty", 90000, "heroine", 4000)

# Display employee details
print("Employee Details:")
emp1.display_employee()
emp2.display_employee()

print("\nFulltime Employee Details:")
emp3.display_fulltime_employee()
emp4.display_fulltime_employee()

# Calculate and print average salary
employees = [emp1, emp2, emp3, emp4]
avg_salary = Employee.average_salary(employees)
print(f"\nAverage Salary of all employees: {avg_salary:.2f}")

Employee Details:
Name: Gopi, Family: Reddy, Salary: 60000, Department: Market
Name: eswar, Family: Bhai, Salary: 70000, Department: Finance

Fulltime Employee Details:
Name: mahesh, Family: babu, Salary: 80000, Department: hero, Bonus: 5000
Name: anushka, Family: shetty, Salary: 90000, Department: heroine, Bonus: 4000

Average Salary of all employees: 75000.00


In [17]:
# Q 2

import numpy as np

# Step 1: Create a random vector of size 20 with floats in the range [1, 20]
vector = np.random.uniform(1, 20, size=20)

# Step 2: Reshape the vector to a 4x5 array
matrix = vector.reshape(4, 5)

# Step 3: Replace the max value in each row by 0 (axis=1)
matrix[np.arange(matrix.shape[0]), matrix.argmax(axis=1)] = 0

# Print the result
print("Modified matrix:\n", matrix)


Modified matrix:
 [[ 0.         16.04979343 11.52826002 14.75961884 12.1579554 ]
 [10.65396818  0.         10.08809239  8.05132105  5.78250891]
 [ 9.82030092 15.34610228  9.60362374  0.          9.58829379]
 [ 8.34198157  5.85733946  0.         13.58484073  4.50765962]]
